"""Regenerate hand-derived fixtures from their canonical inputs.

Re-run with:

    python tests/fixtures/_build_hand_derived.py

Hand-derived fixtures have their expected outputs spelled out in
``derivation.md`` alongside; this script only materializes the input files
(``input.tif``, ``input.csv``) and re-emits the expected CSV/JSON files from
the hand-derived constants encoded below, so a maintainer can verify by hand
that the committed files match the derivation.

Random fixtures are generated by ``_generate_random.py`` (not yet present).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import rasterio
from rasterio.transform import from_bounds

FIXTURES_DIR = Path(__file__).resolve().parent


# ---------------------------------------------------------------------------
# fixture_mt1972_fig3 — Moellering & Tobler (1972), Figure 3 checkerboard.
#
# See reference/raster-R-implementation/scale-variance-example.R (Example 4)
# for the 16x16 integer matrix with values {2, 5, 8}. The paper's published
# totals are TSS = 1152, TDF = 255 (also reproduced in the R reference at
# lines 156-157 of the example file).
# ---------------------------------------------------------------------------

MT1972_FIG3_MATRIX = np.array(
    [
        [2, 5, 2, 5, 2, 5, 2, 5, 5, 8, 5, 8, 5, 8, 5, 8],
        [5, 2, 5, 2, 5, 2, 5, 2, 8, 5, 8, 5, 8, 5, 8, 5],
        [2, 5, 2, 5, 2, 5, 2, 5, 5, 8, 5, 8, 5, 8, 5, 8],
        [5, 2, 5, 2, 5, 2, 5, 2, 8, 5, 8, 5, 8, 5, 8, 5],
        [2, 5, 2, 5, 2, 5, 2, 5, 5, 8, 5, 8, 5, 8, 5, 8],
        [5, 2, 5, 2, 5, 2, 5, 2, 8, 5, 8, 5, 8, 5, 8, 5],
        [2, 5, 2, 5, 2, 5, 2, 5, 5, 8, 5, 8, 5, 8, 5, 8],
        [5, 2, 5, 2, 5, 2, 5, 2, 8, 5, 8, 5, 8, 5, 8, 5],
        [5, 8, 5, 8, 5, 8, 5, 8, 2, 5, 2, 5, 2, 5, 2, 5],
        [8, 5, 8, 5, 8, 5, 8, 5, 5, 2, 5, 2, 5, 2, 5, 2],
        [5, 8, 5, 8, 5, 8, 5, 8, 2, 5, 2, 5, 2, 5, 2, 5],
        [8, 5, 8, 5, 8, 5, 8, 5, 5, 2, 5, 2, 5, 2, 5, 2],
        [5, 8, 5, 8, 5, 8, 5, 8, 2, 5, 2, 5, 2, 5, 2, 5],
        [8, 5, 8, 5, 8, 5, 8, 5, 5, 2, 5, 2, 5, 2, 5, 2],
        [5, 8, 5, 8, 5, 8, 5, 8, 2, 5, 2, 5, 2, 5, 2, 5],
        [8, 5, 8, 5, 8, 5, 8, 5, 5, 2, 5, 2, 5, 2, 5, 2],
    ],
    dtype=np.float64,
)

# Hand-derived expected values — see derivation.md for the arithmetic.
MT1972_FIG3_COMPONENTS = pd.DataFrame(
    {
        "level": [1, 2, 3, 4, 5],
        "scale": [1.0, 2.0, 4.0, 8.0, 16.0],
        "sum_squares": [576.0, 0.0, 0.0, 576.0, 0.0],
        "df": [192, 48, 12, 3, 0],
        "mean_square": [3.0, 0.0, 0.0, 192.0, float("nan")],
        "ss_share": [0.5, 0.0, 0.0, 0.5, 0.0],
        # ms_share denominator: 3 + 0 + 0 + 192 = 195 (last level is NA, excluded).
        "ms_share": [3.0 / 195.0, 0.0, 0.0, 192.0 / 195.0, float("nan")],
        "ss_cumulative": [0.5, 0.5, 0.5, 1.0, 1.0],
    }
)
MT1972_FIG3_TOTALS = {"total_ss": 1152.0, "total_df": 255, "grand_mean": 5.0}


# ---------------------------------------------------------------------------
# fixture_irregular_admin — ragged counties-in-states-in-regions hierarchy.
#
# 2 regions, 6 states, 24 counties. Values and structure chosen to produce
# round-number SS/df at every level for a clean hand derivation. See the
# fixture's derivation.md for the full arithmetic.
# ---------------------------------------------------------------------------

IRREG_ADMIN_ROWS = [
    # (county_id, state_id, region_id, value)
    (1, 1, 1, 10),
    (2, 1, 1, 20),
    (3, 1, 1, 30),
    (4, 2, 1, 8),
    (5, 2, 1, 14),
    (6, 2, 1, 20),
    (7, 2, 1, 26),
    (8, 2, 1, 32),
    (9, 3, 2, 40),
    (10, 3, 2, 50),
    (11, 3, 2, 60),
    (12, 4, 2, 38),
    (13, 4, 2, 44),
    (14, 4, 2, 50),
    (15, 4, 2, 56),
    (16, 4, 2, 62),
    (17, 5, 2, 70),
    (18, 5, 2, 80),
    (19, 5, 2, 90),
    (20, 6, 2, 68),
    (21, 6, 2, 74),
    (22, 6, 2, 80),
    (23, 6, 2, 86),
    (24, 6, 2, 92),
]

IRREG_ADMIN_COMPONENTS = pd.DataFrame(
    {
        "level": [1, 2, 3],
        "scale": [float("nan")] * 3,
        "sum_squares": [1680.0, 3600.0, 10800.0],
        "df": [18, 4, 1],
        "mean_square": [1680.0 / 18, 900.0, 10800.0],
        "ss_share": [1680.0 / 16080, 3600.0 / 16080, 10800.0 / 16080],
        "ms_share": [
            (1680.0 / 18) / (1680.0 / 18 + 900.0 + 10800.0),
            900.0 / (1680.0 / 18 + 900.0 + 10800.0),
            10800.0 / (1680.0 / 18 + 900.0 + 10800.0),
        ],
        "ss_cumulative": [1680.0 / 16080, 5280.0 / 16080, 1.0],
    }
)
IRREG_ADMIN_TOTALS = {"total_ss": 16080.0, "total_df": 23, "grand_mean": 50.0}


# ---------------------------------------------------------------------------


def write_raster_fixture(
    name: str,
    matrix: np.ndarray,
    meta: dict,
    components: pd.DataFrame,
    totals: dict,
    elements: dict[int, pd.DataFrame],
) -> None:
    fdir = FIXTURES_DIR / name
    fdir.mkdir(exist_ok=True)
    (fdir / "expected_elements").mkdir(exist_ok=True)

    nrow, ncol = matrix.shape
    transform = from_bounds(0, 0, ncol, nrow, ncol, nrow)
    with rasterio.open(
        fdir / "input.tif",
        mode="w",
        driver="GTiff",
        height=nrow,
        width=ncol,
        count=1,
        dtype="float64",
        crs=None,
        transform=transform,
        nodata=np.nan,
    ) as dst:
        dst.write(matrix, 1)

    (fdir / "meta.json").write_text(json.dumps(meta, indent=2) + "\n")
    components.to_csv(fdir / "expected_components.csv", index=False)
    (fdir / "expected_totals.json").write_text(json.dumps(totals, indent=2) + "\n")
    for lvl, frame in elements.items():
        frame.to_csv(fdir / "expected_elements" / f"level_{lvl}.csv", index=False)


def write_tabular_fixture(
    name: str,
    rows: list[tuple],
    columns: list[str],
    meta: dict,
    components: pd.DataFrame,
    totals: dict,
    elements: dict[int, pd.DataFrame],
) -> None:
    fdir = FIXTURES_DIR / name
    fdir.mkdir(exist_ok=True)
    (fdir / "expected_elements").mkdir(exist_ok=True)
    df = pd.DataFrame(rows, columns=columns)
    df.to_csv(fdir / "input.csv", index=False)
    (fdir / "meta.json").write_text(json.dumps(meta, indent=2) + "\n")
    components.to_csv(fdir / "expected_components.csv", index=False)
    (fdir / "expected_totals.json").write_text(json.dumps(totals, indent=2) + "\n")
    for lvl, frame in elements.items():
        frame.to_csv(fdir / "expected_elements" / f"level_{lvl}.csv", index=False)


def build_mt1972_fig3_elements() -> dict[int, pd.DataFrame]:
    """Compute per-level element tables from the hand-derived level_rasters.

    Each dataframe has one row per distinct level-n id (0-indexed flat index
    in that level's aggregated raster), columns ``id``, ``mean_child``,
    ``mean_parent``, ``sv``, ``sv_per_df``.
    """
    arr = MT1972_FIG3_MATRIX
    # Level arrays by iterative 2x2 mean aggregation — algebraically identical
    # to direct mean aggregation here since block sizes are constant.
    levels = [arr.astype(np.float64)]
    for _ in range(4):  # 16 -> 8 -> 4 -> 2 -> 1
        lvl = levels[-1]
        nr, nc = lvl.shape
        blocks = lvl.reshape(nr // 2, 2, nc // 2, 2)
        levels.append(blocks.mean(axis=(1, 3)))
    assert levels[-1].shape == (1, 1)
    grand_mean = float(levels[-1][0, 0])
    assert grand_mean == 5.0

    df_per_level = [192, 48, 12, 3, 0]
    out: dict[int, pd.DataFrame] = {}
    for n in range(1, 6):
        lvl_arr = levels[n - 1]
        nr_n, nc_n = lvl_arr.shape
        if n < 5:
            parent = levels[n]
            # Broadcast parent value up to the level-n cell grid.
            parent_up = np.repeat(np.repeat(parent, 2, axis=0), 2, axis=1)
        else:
            parent_up = np.full_like(lvl_arr, grand_mean)
        ids = np.arange(nr_n * nc_n)
        mean_child = lvl_arr.ravel()
        mean_parent = parent_up.ravel()
        sv = (mean_parent - mean_child) ** 2
        dfn = df_per_level[n - 1]
        sv_per_df = np.where(dfn > 0, sv / dfn if dfn > 0 else np.nan, np.nan)
        out[n] = pd.DataFrame(
            {
                "id": ids,
                "mean_child": mean_child,
                "mean_parent": mean_parent,
                "sv": sv,
                "sv_per_df": sv_per_df,
            }
        )
    return out


def build_irregular_admin_elements() -> dict[int, pd.DataFrame]:
    df = pd.DataFrame(
        IRREG_ADMIN_ROWS, columns=["county_id", "state_id", "region_id", "value"]
    )
    state_means = df.groupby("state_id")["value"].mean()
    region_means = df.groupby("region_id")["value"].mean()
    grand_mean = float(df["value"].mean())

    # Level 1: one row per county.
    lvl1 = pd.DataFrame(
        {
            "id": df["county_id"].to_numpy(),
            "mean_child": df["value"].astype(float).to_numpy(),
            "mean_parent": df["state_id"].map(state_means).astype(float).to_numpy(),
        }
    )
    lvl1["sv"] = (lvl1["mean_parent"] - lvl1["mean_child"]) ** 2
    lvl1["sv_per_df"] = lvl1["sv"] / 18

    # Level 2: one row per state.
    states = df.drop_duplicates("state_id").sort_values("state_id")
    lvl2 = pd.DataFrame(
        {
            "id": states["state_id"].to_numpy(),
            "mean_child": states["state_id"].map(state_means).astype(float).to_numpy(),
            "mean_parent": states["region_id"].map(region_means).astype(float).to_numpy(),
        }
    )
    lvl2["sv"] = (lvl2["mean_parent"] - lvl2["mean_child"]) ** 2
    lvl2["sv_per_df"] = lvl2["sv"] / 4

    # Level 3: one row per region.
    regions = df.drop_duplicates("region_id").sort_values("region_id")
    lvl3 = pd.DataFrame(
        {
            "id": regions["region_id"].to_numpy(),
            "mean_child": regions["region_id"].map(region_means).astype(float).to_numpy(),
            "mean_parent": np.full(len(regions), grand_mean, dtype=float),
        }
    )
    lvl3["sv"] = (lvl3["mean_parent"] - lvl3["mean_child"]) ** 2
    lvl3["sv_per_df"] = lvl3["sv"] / 1

    return {1: lvl1, 2: lvl2, 3: lvl3}


def main() -> None:
    write_raster_fixture(
        name="fixture_mt1972_fig3",
        matrix=MT1972_FIG3_MATRIX,
        meta={
            "kind": "raster",
            "description": (
                "Moellering & Tobler (1972) Figure 3 checkerboard. "
                "Gold-standard acceptance fixture: expected TSS=1152, TDF=255 from the paper."
            ),
            "num_levels": None,
            "base_level_factor": 2,
            "agg_fun": "mean",
            "na_handling": "drop_na",
            "crs": None,
            "nrow": MT1972_FIG3_MATRIX.shape[0],
            "ncol": MT1972_FIG3_MATRIX.shape[1],
        },
        components=MT1972_FIG3_COMPONENTS,
        totals=MT1972_FIG3_TOTALS,
        elements=build_mt1972_fig3_elements(),
    )

    write_tabular_fixture(
        name="fixture_irregular_admin",
        rows=IRREG_ADMIN_ROWS,
        columns=["county_id", "state_id", "region_id", "value"],
        meta={
            "kind": "tabular",
            "description": (
                "Ragged 3-level admin hierarchy (counties/states/regions). "
                "Fan-out varies: some states have 3 counties and others 5; "
                "one region has 2 states, another 4. Hand-derived."
            ),
            "value": "value",
            "id_cols": ["county_id", "state_id", "region_id"],
            "agg_fun": "mean",
            "na_handling": "drop_na",
        },
        components=IRREG_ADMIN_COMPONENTS,
        totals=IRREG_ADMIN_TOTALS,
        elements=build_irregular_admin_elements(),
    )

    print("Wrote fixture_mt1972_fig3 and fixture_irregular_admin.")


if __name__ == "__main__":
    main()
